#!/usr/bin/env perl

use warnings;
use strict;
use File::Basename;
use File::Spec;

sub usage{

print <<USAGE;

perl sci [JOURNAL NAME PATTERN]

  This is a program to list sci journals and their impact 
  factor. The JOURNAL NAME PATTERN is actually considered 
  as Perl regular expression, see the following examples.

  sci plant       # Means journals contain 'plant'
  sci 'agri|hort'   # Means journal names contain 'agri' or 'hort'
  sci .           # Means all journals   
  sci ^nat        # Means journals start with 'nat'
  sci sci\$        # Means journals end with 'sci'

USAGE
    exit;
}

sub read_commands{
    usage unless @ARGV;
    my $re = shift @ARGV;
    return $re;
}

sub sci_data_file_name{
    my $filename = q/data.sci.2014.csv/;
    my $dirname = dirname($0);
    my $fullname = File::Spec->catfile($dirname, $filename);
    return $fullname;
}

sub load_sci_data{
    my @journal;
    my $scidata = sci_data_file_name;
    open my $fh, "<", $scidata or die "$scidata: $!";
    my $title=<$fh>;
    chomp($title);
    $journal[0]=[(split(/,/,$title))];
    while(<$fh>){
        chomp;
        my @txt = split(/,/);
        unless($txt[4]){$txt[4] = 0}
        $journal[$txt[0]]=[@txt];
    }
    close $fh;
    return($title, @journal);
}

sub main{
    my $re = read_commands;
    my ($title, @journal) = load_sci_data;

    my @results;
    print STDERR "----Searching: $re\n";
    foreach(1..$#journal){
        if($journal[$_]->[1] =~ /$re/i){
            push @results,$journal[$_];
        }
    }

    unless(@results){
        die "----WARNING: No journals found with names contain the text \"$re\"! Please specify another keyword.\n";
    }

    my $count=0;
    foreach(sort{$b->[4] <=> $a->[4]}@results){
        $count++;
        printf("%4s:|IF=%8.3f |Articles=%6d |ISSN=$_->[2]|Name=$_->[1]\n",$count,$_->[4],$_->[7]?$_->[7]:0);
    }
}

main;
